### ISSUE TITLE
null pointer exception when starting

### ISSUE THREAD

**Issue by 5kt** [ironcore-dev/netdata#236]
**What happened**:
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13f2ec3]

goroutine 1 [running]:
github.com/ironcore-dev/ipam/api/ipam/v1alpha1.(*IPAddr).Equal(...)
	/go/pkg/mod/github.com/ironcore-dev/ipam@v0.2.0/api/ipam/v1alpha1/ipaddr_types.go:49
github.com/ironcore-dev/netdata/controllers.handleDuplicateMacs({_, _}, {{{0x0, 0x0}, {0x0, 0x0}}, {{0x0, 0x0}, {0xc0008003c0, 0x12}, ...}, ...}, ...)
	/workspace/controllers/netdata_controller.go:258 +0x223
github.com/ironcore-dev/netdata/controllers.createIP({{0xc0007f2860, 0xc}, {0xc0008003a8, 0x11}, 0xc00027e488}, 0xc0003200e0, {0x1971e00, 0x2540da0}, {{0x19759d0, 0xc000797e90}, ...})
	/workspace/controllers/netdata_controller.go:325 +0x50e
github.com/ironcore-dev/netdata/controllers.Start()
	/workspace/controllers/netdata_controller.go:448 +0x3d8
main.main()
	/workspace/main.go:46 +0x13b
```

This is happening because of 2 things : 
- filtering is not properly done, it should retrieve IP addresses only from the scanned subnet
- the ip field in spec, in the ip.ipam object can be empty, in this case it should be checked from the reserved field in status

**What you expected to happen**:
Controller should just start normally.

**How to reproduce it (as minimally and precisely as possible)**:
Create an ip.ipam object without specifying the IP address, just the subnet.

**Anything else we need to know**:

**Environment**:

**Comment by rahulppawar** [comment]
IPAM stores IP as reserved in the status. 
IP.spec is nil in this case and it causes nil pointer exception.

IP.spec is checked for nil content before the comparison to solve the issue.
